export function exportOutlineAsMarkdown(outline: any): string {
  const md = [];
  
  // Header
  md.push(`# ${outline.title}\n`);
  md.push(`${outline.description}\n`);
  
  // Course Overview
  md.push(`## Course Overview\n`);
  md.push(`- **Target Audience:** ${outline.targetAudience}`);
  md.push(`- **Duration:** ${outline.totalDuration}`);
  md.push(`- **Course Type:** ${outline.courseType}\n`);
  
  // Learning Objectives
  md.push(`## Learning Objectives\n`);
  outline.learningObjectives.forEach((objective: string) => {
    md.push(`- ${objective}`);
  });
  md.push('');
  
  // Modules
  outline.modules.forEach((module: any, moduleIndex: number) => {
    md.push(`## Module ${moduleIndex + 1}: ${module.title}\n`);
    md.push(`**Duration:** ${module.duration}\n`);
    md.push(`${module.description}\n`);
    
    // Module Learning Objectives
    if (module.learningObjectives && module.learningObjectives.length > 0) {
      md.push(`### Learning Objectives\n`);
      module.learningObjectives.forEach((objective: string) => {
        md.push(`- ${objective}`);
      });
      md.push('');
    }
    
    // Lessons
    if (module.lessons && module.lessons.length > 0) {
      md.push(`### Lessons\n`);
      module.lessons.forEach((lesson: any, lessonIndex: number) => {
        md.push(`#### ${moduleIndex + 1}.${lessonIndex + 1} ${lesson.title} (${lesson.duration})\n`);
        md.push(`${lesson.description}\n`);
        
        if (lesson.activities && lesson.activities.length > 0) {
          md.push(`**Activities:**`);
          lesson.activities.forEach((activity: string) => {
            md.push(`- ${activity}`);
          });
          md.push('');
        }
        
        if (lesson.format && lesson.format.length > 0) {
          md.push(`**Format:** ${lesson.format.join(', ')}\n`);
        }
      });
    }
    
    // Module Activities
    if (module.activities && module.activities.length > 0) {
      md.push(`### Activities & Assessments\n`);
      module.activities.forEach((activity: any) => {
        md.push(`#### ${activity.type}: ${activity.title}\n`);
        md.push(`${activity.description}\n`);
      });
    }
    
    // Module Resources
    if (module.resources && module.resources.length > 0) {
      md.push(`### Resources\n`);
      module.resources.forEach((resource: any) => {
        md.push(`- **${resource.title}** (${resource.type})`);
        if (resource.description) {
          md.push(`  - ${resource.description}`);
        }
      });
      md.push('');
    }
  });
  
  // Course Assessments
  if (outline.assessments && outline.assessments.length > 0) {
    md.push(`## Course Assessments\n`);
    outline.assessments.forEach((assessment: any) => {
      md.push(`### ${assessment.type}: ${assessment.title}\n`);
      md.push(`${assessment.description}\n`);
    });
  }
  
  // Course Resources
  if (outline.resources && outline.resources.length > 0) {
    md.push(`## Course Resources\n`);
    outline.resources.forEach((resource: any) => {
      md.push(`- **${resource.title}** (${resource.type})`);
      if (resource.description) {
        md.push(`  - ${resource.description}`);
      }
    });
    md.push('');
  }
  
  // Footer
  md.push(`---\n`);
  md.push(`*Generated by Course Creation Suite*`);
  
  return md.join('\n');
}

export function downloadMarkdownFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}